version: '3.1'
services:
  db:
    image: mysql
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: commercialdocuments
    ports:
      - "3307:3306"